name: flutter_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^5.3.2
  url_launcher: ^6.1.14
  web_socket_channel: ^2.4.0

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1

  # State management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  flutter_riverpod: ^2.3.6

  # Core
  easy_localization: ^3.0.3
  auto_route: ^7.8.3
  get_it: ^7.6.4

  # Annotation
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code generation
  freezed: ^2.4.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
      - "assets/images/"
      - "assets/animations/"
      - "assets/fonts/"
      - "assets/translations/"